version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
      time: '06:00'
    prefix-add: '[patch]'
  - package-ecosystem: "docker"
    # Location of the Dockerfile
    directory: "/docker-runner"
    # Check for updates every week
    schedule:
      interval: "weekly"
    # The image to monitor for new releases. 
    # Dependabot tracks the versions of the 'actions/runner' on GitHub.
    # It detects that the ARG is tied to this dependency.
    target-branch: "main"
    labels:
      - "runner-update"
      - "dependencies"
    # Specific configuration to monitor the ARG version
    dockerfile-config:
      args:
        # Monitored ARG variable name (must match your Dockerfile)
        - RUNNER_VERSION
