version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: 'homeassistant/home-assistant:latest'
    command: sh -c "pip install meraki && /init"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
    restart: unless-stopped
    ports:
      - '8123:8123'
