[tool.pytest.ini_options]
pythonpath = [
  ".",
  "custom_components"
]
asyncio_mode = "auto"

[tool.mypy]
follow_imports = "silent"

[[tool.mypy.overrides]]
module = "aiofiles"
ignore_missing_imports = true

# Required for the AI-assisted "Gatekeeper" workflow.
[tool.ruff]
fix = true
unsafe-fixes = true
exclude = [".pyenv"]
line-length = 88

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "D",  # pydocstyle
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = ["D100", "D104", "D107", "D211", "D212"]
[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.bumpversion]
current_version = "2.1.0-beta.39"
commit = false
tag = false
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\-beta\\.(?P<beta>\\d+))?"
serialize = [
	"{major}.{minor}.{patch}-beta.{beta}",
	"{major}.{minor}.{patch}",
]

[[tool.bumpversion.files]]
filename = "custom_components/meraki_ha/manifest.json"
search = '"version": "{current_version}"'
replace = '"version": "{new_version}"'

[tool.bumpversion.parts.beta]
first_value = 1
