name: Release

on:
  push:
    branches:
      - main
      - beta

jobs:
  quality-checks:
    uses: ./.github/workflows/reusable-quality-checks.yaml
    with:
      python-version: '3.13'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: quality-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get version
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create Release Asset
        run: |
          mkdir -p release/meraki_ha
          cp -r custom_components/meraki_ha/* release/meraki_ha/
          cd release
          zip -r meraki_ha.zip meraki_ha
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: release/meraki_ha.zip
          tag_name: 'v${{ env.VERSION }}'
          name: 'Release v${{ env.VERSION }}'
          body: 'See CHANGELOG.md for details.'
          prerelease: ${{ github.ref == 'refs/heads/beta' }}
